version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-246-115-40.eu-west-1.compute.amazonaws.com
            database: d3b34110dncctq
            schema: public
            user: uuswdngssgfgex
            password: dfdfc40e8d038ef5f22e28bf3b893feede7505c473c481c83b44ac7aa29045d1
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true